### ISSUE TITLE
Diff script to report changes between PR branches

### ISSUE THREAD

**Issue by clausa20** [infracost/infracost#1192]
I integrated infracost with bitbucket pipelines and every time I update a PR it is executed ok.

But I was expecting to see changes between my branch against the master, but I didn't see any changes reported,
then investigating the diff script, I figure out that infracost checks changes against what is really applied in the infra and it does not check changes between PR branches, so I don't see much sense in reporting changes in the PR.

Could you add some script which reports changes between branches instead of reporting changes against current infrastructure?

**Comment by alikhajeh1** [comment]
@clausa20 thanks for creating this issue! What you describe is exactly how our first prototype [worked](https://www.infracost.io/img/blog/nov-2021-update/original-pull-request-comment.png), but we switched to using the Terraform plan to generate the diff as we kept seeing users who ran Terraform in CI/CD already and so they wanted Infracost to show the same diff as `terraform plan`. However, everyone's workflow is different and a few users have talked about branch diffs too. Out of interest, how do you apply Terraform? from CI/CD or manually?

Here's my current workaround for when I change things on the branch I'm working on and I want to see cost diffs on my laptop:
```
infracost breakdown --path myterraform --format table --out-file infracost1.txt
# make a change to myterraform project
infracost breakdown --path myterraform --format table --out-file infracost2.txt

diff infracost1.txt infracost2.txt
```

A similar thing could be done in CI/CD by switching branches with `git`; it's not ideal though as the output can get messy, it depends on alphabetical output, it needs tricks to get the heading to output, and it doesn't generate the same nice PR comment.

A better way would be to use the `--format json`, and run a [JSON diff](http://jsondiff.com/) between the JSONs, then render the output. I'm not sure if a new `infracost output --format file-diff` makes sense since `output` is designed to combine Infracost JSON files. Maybe `infracost diff` can have an option to take two files and show a diff, but then that only outputs text output, not markdown/JSON/slack messages that are supported by `infracost output --format`. Any other ideas?

**Comment by clausa20** [comment]
@alikhajeh1 We run it using Bitbucket integration with Bitbucket Pipelines for Pull Request.
Could you create a new script (something like bitbucket-diff-branches) contained in the infracost/infracost docker image which calculates diff between the 2 branches specified in the PR with the new estimated cost of that diff?
Maybe that script can do steps you mentioned above.
Thanks.

**Comment by alikhajeh1** [comment]
@clausa20 I'll investigate this more and get back to you next week!

**Comment by alikhajeh1** [comment]
@clausa20 can you possibly help me understand how Terraform runs in your Bitbucket Pipelines? The part that I don't understand is: if Terraform has already applied and deployed resources to the cloud, why is the branch diff needed (doesn't the statefile have the resources that are already deployed?). It might be easier to jump on a quick call, my email is ali@infracost.io if have time.

**Comment by alikhajeh1** [comment]
@clausa20 any update on this?

**Comment by clausa20** [comment]
Hello, in what version do you estimate the script can be available? I've seen that the first version of the script calculates diff from branch and master but it would be great that it takes diff from 2 branches defined in the PR.

**Comment by alikhajeh1** [comment]
@clausa20 sorry for the delay - we've not had time to work on that as we've been working on a way to [parse Terraform HCL code](https://github.com/infracost/infracost/pull/1303) so unfortunately I don't have a date for you. That'll enable us to build something like `infracost breakdown --path branch1 --compare-to branch2`. What we're not sure about is if users want to see the diff between the Terraform HCL code of 2 branches, or if they want to compare the alreadyDeployedTerraformState with branch2? What would work better for you? I assume comparing 2 branches?

**Comment by alikhajeh1** [comment]
@clausa20 just FYI that we're going to start working on `--compare-to` in April :) we'll ping here as soon as we have initial docs so you can review.

**Comment by alikhajeh1** [comment]
@clausa20, @anandnk24 and @brettcurtis can you please check if https://github.com/infracost/infracost/issues/1567 covers your use-cases? Please follow/comment on that issue for updates.

Thanks @clausa20 for sparking this change 🚀

**Comment by alikhajeh1** [comment]
@clausa20 and @anandnk24 the `--compare-to` functionality is live with the **v0.9.23** release. You can check out our docs example [here](https://www.infracost.io/docs/features/cli_commands/#option-1-terraform-directory-1)
