### ISSUE TITLE
No price change when changing `db_instance.performance_insights_retention_period`

### ISSUE THREAD

**Issue by Dinoshauer** [infracost/infracost#1195]
Hey! I just noticed today that infracost doesn't report a price change when changing `db_instance.performance_insights_retention_period`, I would expect it to pick up the change between `7` and `731` and report a price change according to https://aws.amazon.com/rds/performance-insights/pricing/

Here's a link to the slack thread I opened earlier: https://infracost-community.slack.com/archives/C01G63Q4HS7/p1638969459121200

Let me know if you need more info!

I've attached a screenshot of the report from GitHub actions:

![infracost-price-change](https://user-images.githubusercontent.com/2325817/145238563-7081045c-3f1e-457f-8257-11521149f9a8.jpg)

**Comment by alikhajeh1** [comment]
I think we should have logic where if `performance_insights_enabled=true` and `performance_insights_retention_period` is more than 7 days, we show a new cost component:
- name "Long term retention", units "hours", multiply the price by the number of vCPUs based on `instance_class` (so no usage file params are needed).

Since this was one of the early resources we added, we should also review https://aws.amazon.com/rds/pricing/ and ensure that we're covering all the cost components.

**Comment by tim775** [comment]
@Dinoshauer This is fixed and will go out in the v0.9.18 release (should be early next week).  Thanks for the issue!

**Comment by Dinoshauer** [comment]
<img width="510" alt="image" src="https://user-images.githubusercontent.com/2325817/154439760-06425ec9-1aba-4606-92e0-d67ac5d2c475.png">
Looks like it's out and working. Thanks a lot!

**Comment by vdmgolub** [comment]
@Dinoshauer Yep, it is live in v0.9.18 that we released yesterday, but had a small hiccup with Homebrew so delayed the announcement till today :) Thank you for reporting the issue!
