### ISSUE TITLE
Make "Share the Results" link clickable in HTML format

### ISSUE THREAD

**Issue by tim775** [infracost/infracost#1292]
For example:

![image](https://user-images.githubusercontent.com/52185/150154691-176f7b13-6662-4f9b-bc0a-493278fa4f4c.png)

**Comment by alikhajeh1** [comment]
Going to close this issue as most users are moving to using [Infracost Cloud](https://www.infracost.io/docs/infracost_cloud/get_started/) to [share](https://www.infracost.io/docs/infracost_cloud/key_concepts/#team-management) access to all runs with their teams (instead of using HTML exports as that requires them to host those somewhere, setup access control etc).
