### ISSUE TITLE
GCP unsupported resources

### ISSUE THREAD

**Issue by torbendury** [infracost/infracost#1299]
Hello all, I just ran `infracost` on some stuff of ours, and it appears that the following resources are unsupported right now:

```bash
[…]
∙ 9 weren't estimated, report them in https://github.com/infracost/infracost:
  ∙ 3 x google_compute_security_policy
  ∙ 2 x google_cloud_scheduler_job
  ∙ 2 x google_recaptcha_enterprise_key
  ∙ 1 x google_app_engine_application
  ∙ 1 x google_service_networking_connection

```

**Comment by aliscott** [comment]
Thanks @torbendury, we'll look into adding prices for these. In what order would you prioritize them? If you'd like to work on any of them, we'd be more than happy to help too. Our [contributing guide](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#adding-new-resources) gives you a rough idea of what this involves.

**Comment by aliscott** [comment]
Thanks @torbendury and @proffalken. I've created the following issues to track these resources and will close this issue for now. Please watch these for updates on each service:

* https://github.com/infracost/infracost/issues/1356
* https://github.com/infracost/infracost/issues/1357
* https://github.com/infracost/infracost/issues/1358
* https://github.com/infracost/infracost/issues/1359
* https://github.com/infracost/infracost/issues/1360 - @torbendury I've tagged you in a comment here since I'm unsure what pricing applies.
* https://github.com/infracost/infracost/issues/1361

@proffalken for `google_compute_region_ssl_certificate`, is this a free resource?

**Comment by proffalken** [comment]
@aliscott that's a good point, and yes, they are free: https://cloud.google.com/load-balancing/docs/ssl-certificates#ssl-certificate-costs
