### ISSUE TITLE
Infracost March community call

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#1425]
### Join the March Infracost community call!
We're open to discuss any topic related to Infracost and cloud costs - we just shipped our [March updates](https://www.infracost.io/blog/mar-2022-update/). You can also share your adoption challenges and successes. We'll share the latest product news.

### When
Wednesday 9 March 2022, 10:00 PST = 13:00 EST = 18:00 GMT

### Where
Zoom meeting: https://us06web.zoom.us/j/86174507539 
Meeting ID: 861 7450 7539
(this meeting requires a Zoom account for joining, sign up for free on Zoom if you do not have an account)

### Calendar invites
- Google Calendar: go to this [public calendar](https://calendar.google.com/calendar/embed?src=c_fvdtkbmdrqc17m1bmvlhiksb4k@group.calendar.google.com), click on the community call > Copy to my calendar. Alternatively use the email address `c_fvdtkbmdrqc17m1bmvlhiksb4k@group.calendar.google.com` to [subscribe](https://support.google.com/calendar/answer/37100?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Cadd-using-an-email-address).

- iCal format: Use `https://calendar.google.com/calendar/ical/c_fvdtkbmdrqc17m1bmvlhiksb4k%40group.calendar.google.com/public/basic.ics` for other applications.

### Action required
- React with a 👍 - if you intend to join (RSVP)
- Add any topic that you think should be discussed as a comment in this issue.
- Upvote existing comments/topics.

**Comment by 7onn** [comment]
Thanks for caring <3

But I haven't used Infracost but through Atlantis and the state file protection that I've mentioned it isn't actually an issue since my approach is to run `/home/atlantis/infracost_atlantis_diff.sh` after the Atlantis' Terraform plan.

I guess I was just excited talking about the possibility of not accessing the state file due to the HCL parser and therefore sounded wrong.


Btw, tomorrow I'll elaborate issues about:
- Pricing GCP custom instances (e.g: `custom-22-20480` with 22 CPUs and 20GB of ram)
- Discrepancy between the breakdown through the HCL parser and the state file
