### ISSUE TITLE
Support AWS RDS Reserved Instances

### ISSUE THREAD

**Issue by raserma** [infracost/infracost#1575]
AWS EC2 RI is already supported by using the Infracost usage file. Could we extend the support for RDS Reserved Instances as well? Thanks! 🙌 

---

### Infracost details

Add Reserved Instances usage params for [aws_rds_cluster_instance](https://github.com/infracost/infracost/blob/master/internal/resources/aws/rds_cluster_instance.go) and [aws_db_instance](https://github.com/infracost/infracost/blob/master/internal/resources/aws/db_instance.go) resources:

- `reserved_instance_term` string
- `reserved_instance_payment_option` string

And use them when calculating Instance usage cost component. You can use [AWS instance resource](https://github.com/infracost/infracost/blob/master/internal/resources/aws/instance.go#L37-L39) as example.

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/contributing/add_new_resource_guide.md#add-usage-based-cost-components).

**Comment by vdmgolub** [comment]
@raserma Hello! Are you referring to [aws_rds_cluster_instance](https://registry.terraform.io/providers/aaronfeng/aws/latest/docs/resources/rds_cluster_instance) resource? I just checked our cloud pricing API and indeed, it contains prices for RI and it seems like a good idea.

We can follow the same logic AWS Instance does here with usage based params: https://github.com/infracost/infracost/blob/master/internal/resources/aws/instance.go#L37-L39.

Please let me know if you’d like to [contribute](https://github.com/infracost/infracost/blob/master/contributing/add_new_resource_guide.md#add-usage-based-cost-components), otherwise I’ll open it up for the whole community.

**Comment by vdmgolub** [comment]
Sounds good! I'll update your first comment with some details to keep them at the top. :) Thank you for creating the issue! We'll notify here when it's worked on and merged.

**Comment by carmeloriolo** [comment]
Hello! I'd like to help with this issue!
Can I have it assigned?
Thanks :)

**Comment by aliscott** [comment]
Thanks @carmeloriolo I've assigned this to you. Please reach out if we can help in any way 🙏

**Comment by aliscott** [comment]
Thanks @carmeloriolo, tagging @vdmgolub to give this a look when he gets a chance.

**Comment by vdmgolub** [comment]
Hey @carmeloriolo! Apologies for confusion, it's my bad copypasta from the EC2 instance resource. You're right, the pricing will depend only on the Single/Multi-AZ, Term and Payment Option parameters.

Thank you for double checking that! :) I'll update the description. 👍

**Comment by vdmgolub** [comment]
The reservation support has been merge to master and will go out with the next release. Thank you @raserma for creating the issue and thank you @carmeloriolo for contributing! ❤️

**Comment by hugorut** [comment]
Hey all 👋 , this has now been released as part of the [v0.10](https://github.com/infracost/infracost/releases/tag/v0.10.0) release. Thanks again @carmeloriolo for your support 🚀 .
