### ISSUE TITLE
Docker image issues

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#170]
1. Running latest master branch code via `docker run infracost/infracost` shows the help text then panics:
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive (nil chan)]:
main.main()
	/app/cmd/infracost/main.go:183 +0x4e8
```

2. Running `docker run infracost/infracost --version` shows the version then hangs.

3. Running the following still runs the update check:
```
docker run -v $PWD/:/code/ -e INFRACOST_SKIP_UPDATE_CHECK=true -e INFRACOST_API_KEY=xxx infracost/infracost --tfdir /code/

...

A new version of Infracost is available: v0.6.2-21-g823ff9e-dirty → v0.6.2
  $ curl -s -L https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp && \
    sudo mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
```

**Comment by aliscott** [comment]
Fixed in master

**Comment by 06kellyjac** [comment]
docker run -e INFRACOST_SKIP_UPDATE_CHECK=true infracost/infracost version

**Comment by alikhajeh1** [comment]
@06kellyjac it's `--version` as show in `--help`, so `docker run -e INFRACOST_SKIP_UPDATE_CHECK=true infracost/infracost --version` should work as expected but plz lmk if you run into issues.

**Comment by 06kellyjac** [comment]
Sorry I seem to have accidentally commented that :sweat: 

I was looking into a crash I was having and I wanted to see if it was due to my build sandbox having no networking so I was going to run `docker run --network none -e INFRACOST_SKIP_UPDATE_CHECK=true infracost/infracost --version`

Then I found this PR: https://github.com/infracost/infracost/pull/862 I tried making the directory and it fixed the issue! Looking forward to it being in the next release :slightly_smiling_face:
