### ISSUE TITLE
Infracost GKE cost calculation discrepancy with GCP Pricing Calculator

### ISSUE THREAD

**Issue by FelipeLujan** [infracost/infracost#1970]
Hi.

I am using this [basic example](https://github.com/hashicorp/learn-terraform-provision-gke-cluster) for testing infracode out.
It creates the following infrastructure.
<img width="660" alt="image" src="https://user-images.githubusercontent.com/34170261/184574237-025aa409-7e70-479d-b085-728363c80215.png">
+ 1 network and 1 subnetwork.

Infracost generates the following cost breakdown:
```
infracost breakdown --path . --show-skipped
Evaluating Terraform directory at .
  ✔ Downloading Terraform modules 
  ✔ Evaluating Terraform directory 
  ✔ Retrieving cloud prices to calculate costs 

Project: hashicorp/learn-terraform-provision-gke-cluster

 Name                                                      Monthly Qty  Unit   Monthly Cost 
                                                                                            
 google_container_cluster.primary                                                           
 └─ Cluster management fee                                         730  hours        $73.00 
                                                                                            
 google_container_node_pool.primary_nodes                                                   
 ├─ Instance usage (Linux/UNIX, on-demand, n1-standard-1)        4,380  hours       $145.63 
 └─ Standard provisioned storage (pd-standard)                     600  GB           $24.00 
                                                                                            
 OVERALL TOTAL                                                                      $242.63 
──────────────────────────────────
4 cloud resources were detected:
∙ 2 were estimated, all of which include usage-based costs, see https://infracost.io/usage-file
∙ 2 were free:
  ∙ 1 x google_compute_network
  ∙ 1 x google_compute_subnetwork

```

GCP pricing calculator generates the following cost break-down

<img width="411" alt="image" src="https://user-images.githubusercontent.com/34170261/184574927-b19212bc-3a69-49a4-828f-4f980b58b41a.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/34170261/184574946-6ff06e89-900a-4af8-bc98-6b1e2531450c.png">

The management cost for a GKE cluster and the cost of the standard PDs are estimated to cost the same using google's own tool and infracost. But the cost of the actual VMs is significantly different, at 242.63USD vs 305.05USD

Am I missing some configuration?

thanks

**Comment by vdmgolub** [comment]
@FelipeLujan Hello! 👋 Thank you for creating the issue!

The difference you see between Infracost output and the calculator is in the applied "Sustained Use Discount", for N1 instance types it would be 30%: if you check this checkbox the calculator will show the same number as Infracost:
![image](https://user-images.githubusercontent.com/87082/184658750-6bba3410-e399-49c8-ae75-d78f7d460277.png)

Per Google this discount is automatically applied when the instance is used more than 25% of the month ([more info](https://cloud.google.com/compute/vm-instance-pricing#sustained_use)). As Infracost CLI shows usage per full month it automatically applies such discount. This is an expected behavior.

Here's the source code that decides on the discount value for reference: https://github.com/infracost/infracost/blob/master/internal/resources/google/compute_cost_component_helpers.go#L37

Does this solve this issue for you?

**Comment by alikhajeh1** [comment]
Going to close this issue but feel free to re-open if you think we need to make changes.
