### ISSUE TITLE
Add Support for AWS OpenSearch service

### ISSUE THREAD

**Issue by yuha0** [infracost/infracost#1981]
Main TF resource: [aws_opensearch_domain](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain)
Pricing: https://aws.amazon.com/opensearch-service/pricing/

### Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md).

**Comment by vdmgolub** [comment]
Hi! Thank you for creating this issue! Please let us know if you’d like to [contribute](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#adding-new-resources), otherwise we’ll open it up for the whole community (we regularly prioritize and work on them too). We usually add details about each resource listing the cost components Infracost should show. If you have ideas what this could be, you could add them to the issue. We have a guide that explains the process: [Resource mapping guide](https://github.com/infracost/infracost/blob/master/contributing/resource_mapping_guide.md).

**Comment by aliscott** [comment]
@yuha0 this has now been released in [v0.10.21](https://github.com/infracost/infracost/releases/tag/v0.10.21). Thank you @ABaboshin for adding this resource 🙏 

cc'ing everyone who upvoted: @gmeligio, @samiles, @oc-stephen-bennett, @bmbferreira, @nebur1989, @Shrivastava-Varsha, @PatMyron, @ciphero, and @bobsut.
