### ISSUE TITLE
FSX SSD storage unable to be priced

### ISSUE THREAD

**Issue by rogs95** [infracost/infracost#2086]
On a recent CI run when pricing an FSX for windows resource with SSD storage the following appeared in the log and the storage cost for the resource was set to 0:

` time="2022-10-12T13:09:06Z" level=warning msg="No products found for module.fsx.aws_fsx_windows_file_system.storage SDD storage, using 0.00"`

When the storage is set to use HDD then the pricing can be retrieved successfully and when testing with the cloud pricing API, a response is returned when using SSD

Presumably the below should be "SSD" rather than "SDD" to retrieve a price: https://github.com/infracost/infracost/blob/367f1fe9c7e8601f5c1b31ba8ec696593569d71b/internal/resources/aws/fsx_windows_file_system.go#L56

**Comment by tim775** [comment]
Thanks for the issue.  Let me know if you would like to submit a PR for the fix (since you've already done the debugging 🙂).  If so it would be good to add a test case for SSD [here](https://github.com/infracost/infracost/blob/367f1fe9c7e8601f5c1b31ba8ec696593569d71b/internal/providers/terraform/aws/testdata/fsx_windows_file_system_test/fsx_windows_file_system_test.tf).  If not I'll open it up to the community.

**Comment by hugorut** [comment]
hey @rogs95, thanks to @jgrumboe a fix for this has been merged into master. It will go into the next release. Ill let you know when it's available.

**Comment by rogs95** [comment]
great, thanks

**Comment by tim775** [comment]
@rogs95 this is live in v0.10.13
