### ISSUE TITLE
Basic Azure Services not supported?

### ISSUE THREAD

**Issue by djpirra** [infracost/infracost#2191]
Is it correct that the below resources are not supported yet?
They are probably among the most common Azure resources utilized...

- azurerm_linux_web_app
- azurerm_windows_web_app
- azurerm_mssql_server
- azurerm_cdn_frontdoor_profile

Thank you

**Comment by aliscott** [comment]
Hi @djpirra, correct - we welcome [contributions](https://github.com/infracost/infracost/blob/master/CONTRIBUTING.md#adding-new-resources) from the community to help add more and more resource coverage.

For `azurerm_mssql_server` we do support the `azurerm_mssql_database` resource and associate the costs with them instead of the azurerm_mssql_server` resource.

We also support the `azurerm_frontdoor` resource but not the `azurerm_cdn_frontdoor_profile` resource yet.

**Comment by djpirra** [comment]
I have also seen that the azurerm_mssql_database cost returned is different from the one given by the cost panel in azure for the same provisioned resource by a difference of 30$. Is this expected? I would assume base prices for particular service tiers etc would match.

**Comment by aliscott** [comment]
@djpirra do you have an example of the Terraform code you used to generate the cost estimate? If you also have an export/screenshot of the estimate from the Azure cost panel/pricing calculator that will help us debug this issue further.
