### ISSUE TITLE
Use InfraCost with Proxy clearance

### ISSUE THREAD

**Issue by nguyenhung1121990** [infracost/infracost#2461]
Hi team,

My VM is an agent that is running Infracost. VM's already installed docker and other required environments. Our networking is blocked and only allow traffic through forward Proxy server. At moment, the clearance to https://*.infracost.io, https://*.api.infracost.io (https/443) has been done.

Can you please advise if my actions are correcly? before run the infracost, I already set proxy on both OS level and container runtime level (docker at /etc/systemd/system/docker.service.d/http-proxy.conf).
Do I need to pass additional parameters during **docker run infracost/infracost** <bla bla>? 

```
Errors:
  Error sending API request:
    Post "[https://pricing.api.infracost.io/graphql"](https://pricing.api.infracost.io/graphql%22):
      POST https://pricing.api.infracost.io/graphql giving up after 1 attempt(s):
        Post "[https://pricing.api.infracost.io/graphql"](https://pricing.api.infracost.io/graphql%22):
          x509:
            certificate signed by unknown authority
```

**Comment by tim775** [comment]
Hi, first please take a look at the [connection debugging section](https://www.infracost.io/docs/cloud_pricing_api/self_hosted/#cli-fails-to-connect-to-your-cloud-pricing-api) of our self-histored docs and go through the steps there.  Since you're using our hosted api, use that as the endpoint
```
export INFRACOST_PRICING_API_ENDPOINT=https://pricing.api.infracost.io
```

What OS distro is your container running?  The go libraries we use have sometimes had issues with the system certificates in certain environments.  It would be great if I can set something up to reproduce this locally.

In the meantime, as a work around you can try disabling the certificate checking by running 
```
infracost configure set tls_insecure_skip_verify true
```

**Comment by aliscott** [comment]
@nguyenhung1121990 can you please advise if the above helped?

**Comment by nguyenhung1121990** [comment]
Hi, thanks so much.
From OS host, I configured additional user profile config in ~/.docker/config.json and it works. 

Please help to do case closure.
