### ISSUE TITLE
Error on getting module from private repository

### ISSUE THREAD

**Issue by luisve1427** [infracost/infracost#3115]
Error on debug:

2024-06-28T18:31:20Z DEBUG module 'git::[https://HMAIT@dev.azure.com/HMAIT/IT%20Ops/_git/terraform_modules?ref=main'](https://HMAIT@dev.azure.com/HMAIT/IT%20Ops/_git/terraform_modules?ref=main%27) not detected as registry module error="Registry module source is not in the correct format" project_name= project_path=. provider=terraform_dir

Sample of the module usage:

module "vnet" {
  source              = "git::https://HMAIT@dev.azure.com/HMAIT/IT%20Ops/_git/terraform_modules//virtual-networks?ref=main"
}

Pipeline:

          - bash: |
              echo "https://$SYSTEM_ACCESSTOKEN@dev.azure.com" >> ~/.git-credentials
            workingDirectory: $(System.DefaultWorkingDirectory)/main
          - bash: |
              infracost breakdown --path=. \
                --format=json \
                --out-file=$(System.DefaultWorkingDirectory)/infracost-base.json \
                --terraform-var-file="../env/${{ parameters.tf_stage }}/variables.tfvars" \
                --log-level=debug
              echo "Infracost breakdown:"  
              cat $(System.DefaultWorkingDirectory)/infracost-base.json
            workingDirectory: $(System.DefaultWorkingDirectory)/main/iac
            displayName: Generate cost from main branch
            env:
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

**Comment by alikhajeh1** [comment]
@luisve1427 recently we were debugging an issue and saw the same debug line output but it was a false alarm, the issue we had there was the system access token wasn't set, so we tried a personal access token that worked, see https://github.com/infracost/infracost-azure-devops/commit/dd0e01d6062e3e0a58ea63037761920ca8e1bf97 Can you possibly try that to see if that works? 

Also, when you run `infracost breakdown --path=. --variables.tfvars...` locally on your laptop does it download the modules ok? that would be another indication that the issue is related to the access token in CI.

**Comment by luisve1427** [comment]
thanks for the replied, as you said it was an issue on getting the modules, the way that I got it to work was by adding an authorization token.
