### ISSUE TITLE
Make infracost faster

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#332]
A Terraform project with 700 resources takes the following times to run. Download [plan.txt](https://github.com/infracost/infracost/files/5824591/bigplan.txt) and rename to plan.json to try it.

- 4mins with `infracost --tfjson plan.json`, this is hitting the hosted Cloud Pricing API. I haven't yet timed how long it takes if it runs a local version - that would be the next thing to try. If the bottleneck is the CLI itself, we can try a few things such as send 10 parallel price lookup API calls at the same time? Currently we send requests serially.
- 23secs with `curl -X POST -H "x-api-key: my-api-key" -F "tfjson=@plan.json" https://pricing.api.infracost.io/tfjson`. This [just runs the CLI](https://www.infracost.io/docs/integrations#infracost-api) internally but it runs in the same server that the hosted Cloud Pricing API runs.

**Comment by sinabakh** [comment]
It probably needs more in-depth investigation but from the numbers and the nature of the problem, we will probably see a major speedup if we can split the requests and add some level of parallelism to our request sending phase.

**Comment by aliscott** [comment]
Currently we batch the requests by resource. So each resource batches all its cost component queries into one request to the GraphQL API. This happens here: https://github.com/infracost/infracost/blob/master/internal/prices/query.go#L152. I don't think this works well because a lot of resources just have 1 cost component and we loop through them synchronously.

One idea would be to batch every X queries, not-depending on whether they are the same resource or not.
So 2 things we could then play with to improve this are batch size and parallelisation.

The code that loops through the resources to send the requests is here: https://github.com/infracost/infracost/blob/master/internal/prices/prices.go#L31-L39.

**Comment by alikhajeh1** [comment]
Fixed by #347
