### ISSUE TITLE
Automatically add the cost of a repo to the Readme

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#43]
When a user wants to implement an open source project, it would be very helpful to know how much the project will cost. This can be done in an automatic way by updating the Readme file of the project.

This can be done via text, or possibly via a https://shields.io/ button (cost!)

One example: https://github.com/gordonmurray/aws_rds_secrets_manager

**Comment by sashman** [comment]
Having an infracost shield would be so cool!

**Comment by sashman** [comment]
For a shield, we would have to persist some JSON behind an endpoint https://shields.io/endpoint

**Comment by gordonmurray** [comment]
A shield is a great idea! Thanks for including my repo in the example above.

**Comment by unfor19** [comment]
@hassankhosseini - I created this tool [unfor19/replacer](https://github.com/unfor19/replacer) and a GitHub Action which is based on this tool [unfor19/replacer-action](https://github.com/marketplace/actions/replacer-action)

The purpose of the tool
> Auto-update README.md file according to the source code.

So it's possible to run `infracost`, save the output (costs) to a file, and inject the output of the file to README.md

**Comment by alikhajeh1** [comment]
I played around with a few markdown options, feel free to vote on an option in https://github.com/infracost/infracost/issues/605#issuecomment-846437383. @sashman shields.io seems cool!

We could make a small app (that we'll host) that asks the user for: their public git repo URL, a cloud region based on the cloud provider being used, and any variable defaults they need to provide (i.e. all the things we need to run infracost for their project). The app would then need to inject cloud creds (provided by us) so the terraform plan could be fetched. We'd then provide a badge + URL that shows an uptodate cost estimate (we can decide when to update the estimates, every few weeks or when we detect price changes).

**Comment by sinabakh** [comment]
We also could have a Github bot to submit PRs to update the infracost's part of the readme.

**Comment by aliscott** [comment]
I can see this being useful for third-party or shared Terraform modules, but one thing I wonder is how we handle the input variables. For most Terraform modules I've used the cost would depend on the variables passed to the module, so as a user of that module I'd want to be able to specify those, or see some example costs for different options.

**Comment by alikhajeh1** [comment]
Quick update on this: we've released a simple way to [share cost estimates](https://www.infracost.io/docs/features/share_links/) so a link could be added to a readme showing the breakdown. What do people think is a good next step for this? A way of linking to the latest breakdown of a project's cost estimate?

**Comment by brettcurtis** [comment]
I think if you're going to use a badge the badge could link to the shared cost estimates as described above. I almost like the simplicity of adding the text directly to README.md, it's complementary to something like terraform-docs.

**Comment by alikhajeh1** [comment]
@brettcurtis good point, I suppose a way to automate it would be nice, so the readme text/link is always uptodate with the latest main branch's cost estimate?

**Comment by alikhajeh1** [comment]
@brettcurtis that's helpful - with new modules users are flying blind until it's deployed. Another user said something similar today, they are "making a lot of boiler plate code with examples, so it would be possible for teams to put together pretty much a IaC bill of materials and have visibility into how much their projects would cost when stitched together".

If you're up for a 15min demo call, email me (ali.hosseini@infracost.io) as @aliscott's been working on a mind-blowing demo involving [parsing HCL](https://github.com/infracost/infracost/pull/1303) 🕺 

@gordonmurray, @PatMyron, @jgrumboe, @Datawiz0, @billabongrob and @sashman feel free to email me if you'd like to see the demo too, it's very early and runs on our laptops just now...

**Comment by andymac4182** [comment]
Any movement of this? It would be awesome to integrate this with our terraform docs as some resources in an account are from a few different projects so it would be great to be able to see in the docs the approx costs of everything being deployed from a workspace and also the child modules that are all documented with TF docs as well.

**Comment by alikhajeh1** [comment]
@andymac4182 yes! Can you please try the following manual workaround? I haven't tried automating it via a GH Action but it feels like it should be possible - longer term we can make a GH App or something to fully automate this:
1. `infracost configure set enable_dashboard true` (or use the [env var](https://www.infracost.io/docs/features/share_links/))
1. Run `infracost breakdown --path path/to/module --terraform-parse-hcl`
2. Use the generated share-link to create a badge, like this that I created for the terraform-aws-eks module: [![Infracost estimate](https://img.shields.io/badge/Infracost-estimate-5e3f62)](https://dashboard.infracost.io/share/jrr3x118sk6i8wxrck7l1y5kb1r2d4qk)
    ```
    [![Infracost estimate](https://img.shields.io/badge/Infracost-estimate-5e3f62)](https://dashboard.infracost.io/share/jrr3x118sk6i8wxrck7l1y5kb1r2d4qk)
    ```

Other movements in this area are: 
- Right now we're fixing a few remaining issues with the [parse HCL option](https://www.infracost.io/docs/features/cli_commands/#option-3-parse-hcl-directly) (e.g. private module support).
- Right after that, we'll add a way to run diffs by comparing module/repo branches. Notice how the share-link shows $0->$73, once we have the branch-based diff (instead of a plan-based diff), we can also have cost estimate comments on module PRs! 💰 📉 

BTW, if you have 30mins to help us with a usability test on our docs' getting started page, I'd love your help: ali.hosseini@infracost.io :)

**Comment by brettcurtis** [comment]
Sounds good @alikhajeh1 - I added it to my calendar! Just another thought around this is it could be something that happens as part of a pre-commit hook. That's what terraform docs does and now that you guys can parse HCL it might be a good option in the spirit of shifting left :)

**Comment by alikhajeh1** [comment]
@unfor19 thanks! It's got nice workarounds but it's using an older version of Infracost (the interface has changed a lot since then), I think with the parse HCL option simplifies it (e.g. doesn't need cloud creds).

@brettcurtis yep! Infracost is already in [pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform#infracost_breakdown) alongside terraform_docs...
