### ISSUE TITLE
Support cross region AWS Direct connect data transfer costs.

### ISSUE THREAD

**Issue by robh007** [infracost/infracost#488]
Data transfer charges for AWS direct connect are currently calculated from the region where the connection is created. If you use DX gateway you can then incur data transfer costs from a specific region to your DX location. We should look to support both data transfer within the DX Gateway resource & / Or adding support into data transfer usage for AWS region to DX location.

**Comment by alikhajeh1** [comment]
@robh007 can you possibly add some details of what the cost components could be, and which AWS pricing page has the prices for this?

**Comment by tim775** [comment]
Hi @robh007 I was looking into this a bit to understand how the pricing works.  Would make sense to add an `Outbound data transfer` cost component to the existing `dx_gateway_association` resource?  I'm thinking we could get the "fromRegion" from the `associated_gateway_id` and the "location" from the `dx_gateway_id`.

**Comment by tim775** [comment]
I think we can add a new usage cost `Outbound data transfer (from <region>, to <dx location>)` on dx_gateway_association where `<region>` comes from the `associated_gateway_id` and `<location>` comes from the `dx_gateway_id`.  The the cost component from `dx_connection.go` (https://github.com/infracost/infracost/blob/master/internal/providers/terraform/aws/dx_connection.go#L67-L82) can be refactored to be shared with this new cost.

```
 dx_gateway_association.my_dx_connection                                                    
 └─ Outbound data transfer (from us-east-2, to EqDC2)      Monthly cost depends on usage: $0.02 per GB 
```

**Comment by hugorut** [comment]
@alikhajeh1 / @tim775 looking at picking this up this week. Hopeful of PR by weekend if schedule allows 🙏

**Comment by alikhajeh1** [comment]
Thanks!

**Comment by hugorut** [comment]
Ok @alikhajeh1 I had a look at this last night, sadly it doesn't seem like @tim775's suggestion will work.

If we want to create the outbound data transfer on the `aws_dx_gateway_association` we can't get the `location` from the `dx_gateway_id`. The `dx_gateway_id` refers to a `aws_dx_gateway` not the `aws_dx_connection` (which contains the direct connection location information). So in order for us to retrieve the the location information from within the `dx_gateway_association` resource we'd have to traverse a number of resources until we get to the `aws_dx_connection` . Here's a simplistic example below of how a `aws_dx_gateway_association` is linked to the `aws_dx_connection` . 

```go
resource "aws_dx_connection" "this" {
  bandwidth = "1Gbps"
  location = "EqDC2"  // <- what we need
  name = "Test"
}

resource "aws_dx_private_virtual_interface" "this" {
  name = "Test"
  connection_id = aws_dx_connection.this.id
  dx_gateway_id = aws_dx_gateway.this.id

  address_family = "ipv4"
  bgp_asn = 65352
  vlan = 4094
}

resource "aws_dx_gateway" "this" {
  name = "Test"
  amazon_side_asn = "asn-12345"
}

resource "aws_dx_gateway_association" "this" {
  dx_gateway_id = aws_dx_gateway.this.id // <- where we start
  associated_gateway_id = "tgw-123456"
}
```

I'm not sure how we could actually transverse this relationship as `aws_dx_gateway_association` doesn't contain a full reference path back to the `aws_dx_connection`  (`aws_dx_gateway_association` → `aws_dx_gateway` → no reference attribute to pick up). However, perhaps I'm missing something stupid that would make this considerably easier?

In my mind there seems to be two approaches we can take with this issue:

1. Perhaps the best solution to this issue is to introduce [aws_dx_private_virtual_interface](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_private_virtual_interface) & [aws_dx_transit_virtual_interface](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_transit_virtual_interface) as resources and add the costing there. From looking at the terraform docs this seems to be the master point that we can safely have references to both `aws_dx_connection` and `aws_dx_gateway_association` (through `aws_dx_gateway`)
2. Hacky - add a new usage cost map to `aws_dx_connection` which would contain estimates of transfer to different regions, e.g:

```go
monthly_outbound_from_region_to_dx_connection_location:
    eu_west_1: 1000
    us_east_2: 3000
```

What's peeps thoughts? Perhaps you can spot if I'm being considerably stupid with something, but this is how I see it as it stands.

**Comment by hugorut** [comment]
As I wrote the above I realised we actually can't do solution 1. as we don't have a reference from `aws_dx_gateway` to `aws_dx_gateway_association`. Is there some way that we can lookup a resource not using its primary identifier but the a field name. i.e. get all resources in that have `dx_gateway_id` of `x`, whilst in resource `y`?

**Comment by alikhajeh1** [comment]
@hugorut thanks for the awesome deep-dive! Just FYI about:
- https://github.com/infracost/infracost/blob/master/internal/providers/terraform/aws/route53_record.go#L13-L18 as `ReferenceAttributes` can be multiple layers. 
- https://github.com/infracost/infracost/issues/849

Would any of those help in this case? If not, it feels like we need to create a new GH issue to explain use-case (get all resources in that have dx_gateway_id of x, whilst in resource y) and mention this resource in there as an example.

The usage file option isn't that bad either, specially given https://github.com/infracost/infracost/discussions/985.

**Comment by hugorut** [comment]
@alikhajeh1 ah yeah #849 is pretty much exactly what I was thinking with the "dx_gateway_id of x, whilst in resource y" scenario. Albeit much better worded! So it seem's until #849 is implemented that the usage file is basically the way to go. I'll work on a draft PR so we can get some 👀  on it and see if we like it.

**Comment by tim775** [comment]
@robh007 @guilhermerenew this will go live in the next release (0.9.10).  Thanks @hugorut!
