### ISSUE TITLE
Add support for Azure legacy VMs

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#675]
Terraform resources: azurerm_virtual_machine and azurerm_virtual_machine_scale_set
Pricing details: https://azure.microsoft.com/en-us/pricing/details/virtual-machines/windows/ and https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/

Ping @aliscott before starting to work on this as I think he worked on the non-legacy versions of these resources

**Comment by aliscott** [comment]
What I've found so far:

To find if it's a windows or Linux VM we should assume Linux for default. If either `storage_os_disk.os_type == "Windows"` or `storage_image_reference.offer == "WindowsServer"` then we should use Windows. We can then use the existing `linuxVirtualMachineCostComponent` and `windowsVirtualMachineCostComponent` cost components.

We should also add a cost component for `Ultra disk reservation (if unattached)` using the existing `ultraSSDReservationCostComponent` function.

We should also have the following subresources:
* `storage_os_disk` is similar to the `osDiskSubResource`, using the `managedDiskCostComponents` function. We could either copy the logic from here or refactor the `managedDiskCostComponents` function to take `diskType` as an argument, since this resource uses `managed_disk_type` instead of `storage_account_type`.

* `storage_data_disk[x]` is an array of additional disks and should add more disks similar to `storage_os_disk`.

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it!

**Comment by alikhajeh1** [comment]
@ekifel the master branch test logs are showing this, can you please check? 
```
time="2021-05-26T17:14:57Z" level=warning msg="No products found for storage_data_disk Disk operations, using 0.00"
time="2021-05-26T17:14:57Z" level=warning msg="No products found for storage_data_disk Disk operations, using 0.00"

```
