### ISSUE TITLE
Add support for Azure CDN

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#708]
Pricing: https://azure.microsoft.com/en-us/pricing/details/cdn/
Terraform resources: azurerm_cdn_profile and azurerm_cdn_endpoint

**Comment by tim775** [comment]
Terraform resource `azurerm_cdn_endpoint` should have

- A `monthly_outbound_gb` usage parameter displayed as `Outbound data transfer (<type>, <tier>)` with unit `GB` where type is determined by the azure_cdn_profile.sku (e.g. 'Standard Microsoft', 'Standard Akamai',...) and tier is the pricing tier (e.g. 'first 10 TB', 'next 40 TB', etc...).  When the usage key is not provided, all tiers should be displayed.  When it is provided, only the tiers with a charge should be displayed.
- `Rules engine rule (over 5)` with the count determined by the total number of `global_delivery_rule` + `delivery_rule` blocks in the endpoint.
- A `monthly_rules_engine_requests` usage parameter displayed as `Rules engine requests` unit `1M requests`.  This should only appear if at least one `global_delivery_rule` or `delivery_rule` block has been defined.
- When the endpoint has `optimization_type` == `DynamicSiteAcceleration`, `monthly_outbound_gb` should be used to diaply `Acceleration outbound data transfer (<tier>)` with unit `GB`  and tier is the pricing tier.  Again, when the usage key is not provided, all tiers should be displayed.  Otherwise, only the tiers with a charge should be displayed.

**Comment by ekifel** [comment]
@alikhajeh1, Hey, I want to work on it!
