### ISSUE TITLE
Error when AzureRM App Service Custom Hostname Binding is in Terraform environment

### ISSUE THREAD

**Issue by holzro** [infracost/infracost#752]
I get the following error when trying to generate an Infracost breakdown using Infracost 0.8.7. This only happens when there is an AzureRM App Service Custom Hostname Binding in the Terraform environment 

```
❯ infracost breakdown --path ./
Detected Terraform directory at ./
  ✔ Running terraform plan

Error: An unexpected error occurred

runtime error: index out of range [0] with length 0
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x10001000264cc30, 0x6)
	runtime/debug/stack.go:24 +0x9f
main.handleUnexpectedErr(0xc0001a7ba0, 0x1752800, 0xc00014a1c8)
	github.com/infracost/infracost/cmd/infracost/main.go:220 +0x45
main.main.func1(0xc000159ec8, 0xc0001a7ba0, 0xc00012a240)
	github.com/infracost/infracost/cmd/infracost/main.go:39 +0xa5
panic(0x1752800, 0xc00014a1c8)
	runtime/panic.go:965 +0x1b9
github.com/infracost/infracost/internal/providers/terraform/azure.NewAzureRMAppServiceCustomHostnameBinding(0xc0000b8f80, 0x0, 0xc0007b75fe)
	github.com/infracost/infracost/internal/providers/terraform/azure/app_service_custom_hostname_binding.go:26 +0xa0c
github.com/infracost/infracost/internal/providers/terraform.(*Parser).createResource(0xc000159710, 0xc0000b8f80, 0x0, 0x0)
	github.com/infracost/infracost/internal/providers/terraform/parser.go:66 +0x174
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSONResources(0xc000159710, 0x35b01, 0x1c4cb48, 0x0, 0x0, 0xc00007c0c0, 0x5, 0xc000792000, 0x35b04, 0x0, ...)
	github.com/infracost/infracost/internal/providers/terraform/parser.go:114 +0x4da
github.com/infracost/infracost/internal/providers/terraform.(*Parser).parseJSON(0xc000159710, 0xc000756000, 0x35b04, 0x3c000, 0xc00007c0c0, 0x0, 0x1, 0x1, 0x7, 0x0, ...)
	github.com/infracost/infracost/internal/providers/terraform/parser.go:134 +0x72a
github.com/infracost/infracost/internal/providers/terraform.(*DirProvider).LoadResources(0xc0001667e0, 0xc00007c0c0, 0x0, 0xc00007c0c0, 0x0)
	github.com/infracost/infracost/internal/providers/terraform/dir_provider.go:104 +0x145
main.runMain(0xc00024e000, 0xc0001a7ba0, 0x0, 0x0)
	github.com/infracost/infracost/cmd/infracost/run.go:78 +0x3be
main.breakdownCmd.func1(0xc00024e000, 0xc00013b3e0, 0x0, 0x2, 0x0, 0x0)
	github.com/infracost/infracost/cmd/infracost/breakdown.go:40 +0x106
github.com/spf13/cobra.(*Command).execute(0xc00024e000, 0xc00013b3c0, 0x2, 0x2, 0xc00024e000, 0xc00013b3c0)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000217680, 0x351, 0xc000159ee8, 0x7)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	github.com/infracost/infracost/cmd/infracost/main.go:171 +0xc19

Environment:
Infracost v0.8.7
```

**Comment by alikhajeh1** [comment]
Thanks for reporting this! since [`azurerm_app_service_custom_hostname_binding`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_custom_hostname_binding) does not have a `location` property, we lookup its `resource_group_name.location` and use that to find the price for that region. The issue here seems to be that the `resource_group_name` is not defined in this TF project? Is it defined in another project? Or do you know of a better way we can find the location?

I've sent [a PR](https://github.com/infracost/infracost/pull/754) so we skip this resource if we can't find its location.

**Comment by holzro** [comment]
The azurerm_app_service_custom_hostname_binding resource is deployed as a part of a module, but the azurerm_resource_group is not a part of the module. So azurerm_resource_group.locaton is passed to the module input, and that input variable is used for the location on azurerm_app_service_custom_hostname_binding

**Comment by alikhajeh1** [comment]
Here's what we do to find the location for Azure just now:

1. parse location from the Terraform resource if it exists.
2. otherwise parse the location from a parent Terraform resource if it exists. E.g. `azurerm_mssql_database` points to `azurerm_mssql_server`, which has location.
3. otherwise parse the location from the resource group.

Here's what we could do next, any feedback on which options you think work best?

4. use the Azure API to find the location of the resource, either directly or via it’s resource group if the resource already exists in the cloud. This only works when Infracost is run against a Terraform project dir (not plan JSON since that doesn't have creds), or if the user sets creds we should use via env vars.
5. let the user define the default in [usage file](https://www.infracost.io/docs/usage_based_resources) `azure.default_region` (easy to implement)
6. let the user override the `azure.default_region` on a per-resource basis using `region` (easy’ish to implement)
7. otherwise fall back to eastus (easy to implement)

Also, can you possibly paste an example of the module input you mentioned above? That helps check if our logic is missing something.

**Comment by holzro** [comment]
Here is the custom hostname binding snippit

```
resource "azurerm_app_service_custom_hostname_binding" "app" {
  hostname            = var.hostname
  app_service_name    = azurerm_app_service.app.name
  resource_group_name = var.resource_group_name
  ssl_state           = "SniEnabled"
  thumbprint          = azurerm_app_service_certificate.app.thumbprint
}
```

var.resource_group_name is a module input. No location setting is defined, as this is not expected in this resource
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_custom_hostname_binding

**Comment by alikhajeh1** [comment]
Thanks @holzro - I've merged the fix as the prices for `azurerm_app_service_custom_hostname_binding` were not region-specific. We'll cut a new release in the next day or two so we can address some of the other bugs.
