### ISSUE TITLE
Add support for ECS with EC2 launch type

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#79]
Infracost currently supports ECS with Fargate launch type, but not EC2 launch type.

**Comment by richardj-bsquare** [comment]
For anyone with a micro-service architecture, ECS with EC2 (ASGs) is 90% of the cost of an AWS deployment. Unfortunately its quite complex, since ECS itself doesn't dictate the potential costs, but rather the associated scaling groups associated with metrics or via a Capacity provider. 

I think this means to support this all we have to change the existing ECS support to set cost to free for ECS with EC2. Then the ASG (which infracost supports) typical-usage dictates the price.

**Comment by alikhajeh1** [comment]
Thanks for the comment @richardj-bsquare, I added this to the priority list yesterday as I saw the 2 👍. 
@aliscott had previously looked at how we could work out from the task definitions, how many instances would be needed in the autoscaling groups to satisfy the desired_count of the service. But this required implementing the same scheduling logic that [AWS use](https://aws.amazon.com/blogs/containers/how-amazon-ecs-manages-cpu-and-memory-resources/). As a first cut of this now, we could use the Infracost [usage-file](https://www.infracost.io/docs/usage_based_resources#infracost-usage-file) for getting the expected instance count of the autoscaling group - would that be useful for you?

**Comment by richardj-bsquare** [comment]
I think that would be a great compromise.

**Comment by alikhajeh1** [comment]
Thanks @richardj-bsquare - I bumped up the priority of this ticket on the [board](https://github.com/infracost/infracost/projects/2).

**Comment by sinabakh** [comment]
I'm interested to work on it.

**Comment by alikhajeh1** [comment]
@tsouza85 and @richardj-bsquare support for this was released in v0.7.20 🎉 The [`aws_autoscaling_group.instances`](https://github.com/infracost/infracost/blob/master/infracost-usage-example.yml#L181-L182) usage file parameter can be used to set the number of instances. Would be great to hear your feedback about [our approach](https://www.infracost.io/docs/usage_based_resources) towards usage-based resource in general.

**Comment by richardj-bsquare** [comment]
Great thanks, I'll trial the usage-based stuff and see how well my predicted costs match actual.

**Comment by richardj-bsquare** [comment]
A quickbit of feedback, I'm getting some anomalous output in the cost report where a sub-part of the displayed tree is completely unrelated to the resource in question, best explained by example:

```
module.companion.aws_autoscaling_group.cluster-service-on-demand                                                                                                                       
  └─ module.companion.module.unrelated-module.null_resource.wth                                      
     ├─ Linux/UNIX usage (on-demand, )                                                                                          7,300  hours          0.0000       0.0000        0.0000  
     └─ root_block_device                                                                                                 
        └─ General Purpose SSD storage (gp2)                                                                                       80  GB-months      0.1000       0.0110        8.0000
```

**Comment by alikhajeh1** [comment]
So `module.companion.aws_autoscaling_group.cluster-service-on-demand` and `module.companion.module.unrelated-module.null_resource.wth` share the same "root" module but are separate resources? Is `null_resource` really a TF null_resource or sanitized in that output?

It would be useful if you can share the terraform snippet/resource that lead to that output. The instance type should be after "on-demand" output so that missing is probably related to the price showing 0. You can also DM me on [the community Slack](https://infracost.io/community-chat) if you prefer to share that privately.

**Comment by richardj-bsquare** [comment]
Yes, it really is a null_resource; I only masked 'unrelated-module' and 'wth' for customer privacy reasons.

I didn't actually fill out the infracost-usage.yml; so I'll do that first.

**Comment by alikhajeh1** [comment]
@richardj-bsquare cool - can you please create a separate issue when you've had a chance to try it with the infracost-usage.yml too? Seems like a bug :) Also, if you run it with `--log-level=debug`, there should be lines like "No products found for" or "No prices found for", those lines plus any repro steps would help us debug much faster.
