### ISSUE TITLE
Add Atlantis support

### ISSUE THREAD

**Issue by hassankhosseini** [infracost/infracost#81]
Users who want to make IaC CI/CD easier and want to use Atlantis would find this addition very useful.

https://www.runatlantis.io/
https://github.com/runatlantis/atlantis

**Comment by mwarkentin** [comment]
I'd be interested in this. :)

**Comment by alikhajeh1** [comment]
Atlantis [doesn't seem to have](https://github.com/runatlantis/atlantis/issues/1221) a way for 3rd parties to integrate into it. However, if Atlantis is run via their Docker image, we can create a [custom atlantis image](https://www.runatlantis.io/docs/deployment.html#customization) to install infracost, then infracost can be run as [a custom command](https://www.runatlantis.io/docs/custom-workflows.html#use-cases), probably before apply? I guess we'd then want infracost to [detect the git application](https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh#L84-L115) being used and post a comment with the diff of master vs PR costs?

Anyone have other thoughts on this?

**Comment by jamengual** [comment]
Since Atlantis holds the plan after comment command is run like `atlantis plan` it is possible to grab the plan and send it over to infracost for evaluation it will be ideal not to use a custom docker image and instead an integration is build on atlantis or better yet a plugin/integration feature could be build to integrate things like infracost.

**Comment by alikhajeh1** [comment]
@jamengual that's an interesting idea! If we had an HTTP API that would accept similar options as the CLI, `curl` can be used to send the [plan JSON file](https://www.infracost.io/docs/#3-terraform-plan-json) and get back the response (table, json, html). Depending on how the terraform project is structured, the plan json file might have cloud creds, but those could be [stripped out](https://gist.github.com/hsuh/88360eeadb0e8f7136c37fd46a62ee10#file-aws-access-key-grep-L10-L11) before being sent to the HTTP API as Infracost doesn't want/need them. How does that sound?

**Comment by magichair** [comment]
I find that I run a custom atlantis docker image for my deployments. We needed some external things provided on the base image for custom providers. While it's not the easiest plug & play experience to document, it wasn't too bad for me since I already took these steps.

Sample simple Dockerfile:
```Dockerfile
FROM runatlantis/atlantis

RUN \
    curl -s -L https://github.com/infracost/infracost/releases/latest/download/infracost-linux-amd64.tar.gz | tar xz -C /tmp && \
    mv /tmp/infracost-linux-amd64 /usr/local/bin/infracost
 ```
 
 I was able to get some basics of this setup (just last night) this way. We use this terraform module for managing our Atlantis rollout - https://registry.terraform.io/modules/terraform-aws-modules/atlantis/aws/latest

Couple of steps:
* I provide the `INFRACOST_API_KEY` in the `custom_environment_variables` parameter
* Rather than baking in a [server-side repo config](https://www.runatlantis.io/docs/custom-workflows.html) for the custom workflow I put the following in the `ATLANTIS_REPO_CONFIG_JSON` `custom_environment_variables`:
```hcl
locals {
  server_side_repo_config = {
    repos = [
      {
        id = "/.*/"
        workflow = "infracost"
      }
    ]
    workflows = {
      infracost = {
        plan = {
          steps = [
            "init",
            "plan",
            {run = "TERRAFORM_BINARY=/home/atlantis/.atlantis/bin/terraform$ATLANTIS_TERRAFORM_VERSION infracost --no-color --tfplan $PLANFILE 2>/dev/null"}
          ]
        }
      }
    }
  }
}
...snip...
  custom_environment_variables = [
    {
      name  = "ATLANTIS_REPO_CONFIG_JSON",
      value = jsonencode(local.server_side_repo_config)
    },
...snip...
```

**Comment by alikhajeh1** [comment]
@jamengual and @mwarkentin I just released the Infracost API so `curl` can be used with a Terraform plan JSON: https://www.infracost.io/docs/integrations#infracost-api Please let me know if you find it useful. I'm setting up a test Atlantis deployment so I can write better docs for that integration.

@magichair that is awesome - thank you! I'll take it for a spin and include it as an option in the Atlantis integration docs.

**Comment by jamengual** [comment]
Awesome, @alikhajeh1 I think a bit more detail on the payload will be useful but it can be still worked out from the curl output.

**Comment by alikhajeh1** [comment]
A big thank you to everyone for their feedback so far! The Infracost Atlantis integration has been released 🎉 
See [this pull-request for a demo](https://github.com/infracost/infracost-atlantis/pull/2#issuecomment-773427685), expand the Show Output sections and scroll down to see the Infracost output.

Please see [this repo's README](https://github.com/infracost/infracost-atlantis/) for the docs, which describe the two usage methods:
1. Using a custom Docker image, thanks to @magichair for sharing the script he used with us. 
2. Sending the `$PLANFILE` from Atlantis to the Infracost API with `curl`, thanks to @jamengual for this idea.

I'm going to close this issue but feel free to add comments here or create new issues for follow-ups. This is just the start, we have plans to keep iterating on this integration; I've also joined the Atlantis Community Slack and am happy to help anyone who runs into issues.

cc @mwarkentin, @robh007, @JoshiiSinfield, @lindsaygrace, @aelbozie, @magichair, @mhmdio, @dawidmalina, @rexrafa, @jamengual
