### ISSUE TITLE
Support internal Terraform state representation

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#811]
Currently we support the state JSON representation that is generated by running `terraform show -json`.
We could also look at supporting the state snapshot representation since it is also JSON, however, this may be more difficult since it might not work with remote backends and is subject to change.

> State snapshots are stored in JSON format and new Terraform versions are generally backward compatible with state snapshots produced by earlier versions. However, the state format is subject to change in new Terraform versions, so if you build software that parses or modifies it directly you should expect to perform ongoing maintenance of that software as the state format evolves in new versions.
(https://www.terraform.io/docs/language/state/index.html#format)

The use case for this is for when the state is pulled from a remote backend directly. Without support for this, the user needs to also pull the project code and use the terraform binary to convert the internal state representation to the supported state JSON.

If we cannot support this, then one option is to at least recognise this format and show an appropriate error message with instructions on how to generate the supported. state JSON.

**Comment by alikhajeh1** [comment]
@1mamute can you possibly share a bit more about how Infracost is used in your workflow? Most users we see run Infracost before `terraform apply`, but this sounds like you want to run Infracost after, to see a breakdown of the current costs? If so, what's the purpose for this? as a sanity check?

**Comment by 1mamute** [comment]
> @1mamute can you possibly share a bit more about how Infracost is used in your workflow? Most users we see run Infracost before `terraform apply`, but this sounds like you want to run Infracost after, to see a breakdown of the current costs? If so, what's the purpose for this? as a sanity check?

I've been running infracost in two scenarios:
- `infracost diff` before `terraform apply` so we can see in the merge request approximately how much the changes will cost. We use this to see the cost **diff**erence between our actual state file and the configuration we are planning to apply.
- `infracost breakdown` in a scheduled pipeline that runs everyday at 8am. In this pipeline, I run `infracost breakdown` for every state files (we have 3 at the moment) and generate a uniform JSON report with `infracost ouput *json --format json > report.json` that gets parsed and sended to our Discord channels and Google Sheets. See the example below. We use this to see a general cost estimation for our cloud infraestructure.

![image](https://user-images.githubusercontent.com/22196761/122060271-d0c7bd80-cdc3-11eb-87ed-a87ffbd2c5d5.png)

> **Why use infracost to do this instead of any AWS cost and budget report?**  

We actually use both, because they complement well each other.  AWS provides a great cost forecast and running cost breakdown and Infracost provides a way to estimate how much our whole infrastructure costs (This information is difficult to gather in AWS).  

With infracost I can use the usage file to refine even more the cost estimation report (a big on is setting our dev environment to only 12 hours/day).

**Comment by 1mamute** [comment]
We're still pretty dependent on the Terraform binary to generate the JSON output that Hashicorp recommends to ingest. Seems like terraform-exec wouldn't help much. https://github.com/infracost/infracost/issues/821#issuecomment-864973421

The internal state JSON's is on version 4 for quite some time now and Hashicorp says (but don't promise) that it will be _generally_ [backwards compatible](https://www.terraform.io/docs/language/state/index.html#format). I'm pretty sure that's worth doing, we just need to keep an eye open for any changes in the schema.

**Comment by tim775** [comment]
I was thinking about what would be involved in actually parsing the tfstate.  Please forgive (and correct) all my misunderstandings and flawed assumptions 🙂:

Initially it seems straightforward because we usually only need a few attributes from a resource so it's just a matter of discovering the correct json path for them.  But how do we discover those paths?  

Working with the plan.json is pretty straightforward because we can generate examples from a tf config during dev and testing.  Where do we get the tfstate files to work with?  Is it possible to generate them from a plan or do we have to actually launch resources?

If we can't get tfstate for dev/test, then we need a really concrete understanding of each resource's schema.  I assume the source of truth for those are schemas in the terraform provider plugins (e.g. https://github.com/hashicorp/terraform-provider-aws/aws).  We could just look at the schema and figure out the json paths, but we would still need tfstate files to test.  So instead we import the plugin packages to infracost and use them to parse tfstate into a usable format.  At this point are we just re-implementing a less flexible (and likely buggier)`terraform show` inside infracost?

**Comment by aliscott** [comment]
> Where do we get the tfstate files to work with? Is it possible to generate them from a plan or do we have to actually launch resources?

Yeah, we would have to launch resources to generate these. All the arguments we use currently for each resource should be available in the state JSON. The file contains everything listed under the "Attributes Reference" sections in the Terraform docs (example: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#attributes-reference), and each of these says "In addition to all arguments above".

**Comment by alikhajeh1** [comment]
> Without support for this, the user needs to also pull the project code and use the terraform binary to convert the internal state representation to the supported state JSON.

Is this problem addressed with the new [v0.10 release](https://www.infracost.io/docs/guides/v0.10_migration/) that parses Terraform HCL code directly? Since Infracost can now run in source control systems, without the need for the terraform binary.

**Comment by alikhajeh1** [comment]
Going to close this issue as I've not heard from users that need this, https://www.infracost.io/docs/features/cli_commands/#option-1-terraform-directory is the way to go I think
