### ISSUE TITLE
Investigate using terraform-exec to wrap the Terraform commands

### ISSUE THREAD

**Issue by aliscott** [infracost/infracost#821]
Currently Infracost calls out to a Terraform binary. The problem with this is that it requires the user to have the Terraform binary pre-installed, which is rarely the case in CI/CD systems.

We could look at using the [terraform-exec](https://github.com/hashicorp/terraform-exec) package to install Terraform automatically and wrap the Terraform commands.

See some [previous discussion here](https://github.com/infracost/infracost/issues/817).

**Comment by 1mamute** [comment]
The idea in using [terraform-exec](https://github.com/hashicorp/terraform-exec) would be to minimize the dependency on the Terraform binary for infracost users. Yet, reading through the code, seems like the module only downloads the terraform binary in the system and then wraps the terraform CLI commands.

I mean, we're already wrapping the terraform commands, so just refactoring here.  
Downloading Terraform wouldn't solve the binary dependencies, in fact, it actually makes it worse because we wouldn't be able to use another binary like we already do in **infracost** through the `INFRACOST_TERRAFORM_BINARY` env variable. I think that's possible to implement but that means another refactoring.

I think that the main benefit in using [terraform-exec](https://github.com/hashicorp/terraform-exec) would be to not have to manipulate the JSON's files in the filesystem like I said in this https://github.com/infracost/infracost/issues/817#issuecomment-862848877.

**Comment by alikhajeh1** [comment]
Seems like we can close this issue? We're prototyping a new way to integrate Infracost into CI/CD pipelines that involves steps such as TF install (e.g. with [this](https://github.com/hashicorp/setup-terraform)) to happen before Infracost is run.
To remove the TF binary dependency altogether, we'd need to parse the HCL code or do https://github.com/infracost/infracost/issues/811

**Comment by aliscott** [comment]
Agree, I'll close for now and we can re-open if there's another use case.
