### ISSUE TITLE
Add support for Azure Virtual Desktop

### ISSUE THREAD

**Issue by alikhajeh1** [infracost/infracost#888]
From [this PR comment](https://github.com/infracost/infracost/pull/886#discussion_r679387103):
 alikhajeh1: Looking at https://azure.microsoft.com/en-us/pricing/details/virtual-desktop/, I assume the user has to provision the VMs so we'll show costs for those, and there's no additional fee for "configuring" the VMs with desktop apps? Sorry if that's a dump question, I haven't used these resources before...

Theragus: Usually, the Host Pool is where the charges will apply because that's where the "work" is being done.
These are the infrastructure costs that are not influenced by the amount of Desktop Apps or Remote Apps that are configured. The other cost part is related to M365/O365 Licensing, which is not showing up in any Azure Bill.

**Comment by Theragus** [comment]
A small note on this one. 
For AVD, the costs are basically the same as any VM, Microsoft does not charge any additional costs, apart from the O365/M365 licenses, and the usual stuff like Managed Disks etc...
For AVD there is only the host pool that uses x times the same VM Size.

**Comment by alikhajeh1** [comment]
@Theragus I started looking into this as @vdmgolub was looking for an issue to work on... Looking into  https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_desktop_host_pool it looks like we might want to add it as a free resource since as you mentioned, the license costs are separate from Azure bills, and the rest is already resources we cover.

Or do you think something like the Azure Price Calc for AVD is useful, where users define the same input params as the calculator in the [usage file](https://www.infracost.io/docs/usage_based_resources) and we calculate the costs? That risks outputting the VM costs twice but it does enable easy/quick what-if analysis, and the estimates could then be checked into the repo so they can be adjusted and tracked vs actuals later on.

**Comment by Theragus** [comment]
@alikhajeh1 I'm currently looking into it and I'm a little bit confused how terraform is actually handling the VMs here. For me, it seems like there is no way from the azurerm provider side to control the number or size of the VMs that are added to the host pool. In the API and in the Portal it sure is possible to create a host pool without creating VMs, see the screenshot.

<img width="657" alt="Bildschirmfoto 2021-09-23 um 23 36 58" src="https://user-images.githubusercontent.com/38653346/134587600-a08760a3-98fd-416a-8ea3-a373d4104110.png">

I'm currently testing how HashiCorp is expecting us to add the VMs to this Host Pool via terraform, because I also can't see any way in the provider to add the VMs afterwards. Either it has to be done manually afterwards or I'm completely overlooking something here.
Usually, you can just define the VM size alongside the host pool and then you could just take the size of the VMs and check that against your existing VM Pricing API.
If this is not the case with this resource then you could go ahead and define it as a free resource.

**Comment by alikhajeh1** [comment]
Thanks @Theragus! I really appreciate you digging into this, once we know the outcome of that investigation we'll add it to the project board (either to be added as a free resource or coded with cost components).

**Comment by Theragus** [comment]
@alikhajeh1 I looked into this now and I think I get the picture now.
after looking at the terraform azurerm provider repo and also at this post here https://www.nathannellans.com/post/deploying-azure-wvd-with-terraform it seems that there is only a registration token generated that is then used by normal VMs to connect and register to the Host Pool.

Therefore the Host Pool incurs no charges itself and could be added as a free resource since VMs are already covered. I'm gonna add it to the repo later today and open a PR.
