### ISSUE TITLE
`output` not properly handling globbing

### ISSUE THREAD

**Issue by nomeelnoj** [infracost/infracost#927]
Hello! Thanks for the awesome tool!

In our terraform repo, we have 1000s of states.  Nearly every resource is in its own state, as this enables extremely rapid development as users are very unlikely to be working in the same state.  When we run our CI, we pick up the changes and run a matrix build to run the all the changed states in parallel.  Therefore, the out of the box action will not work, as we want to aggregate all the infracost reports into a single file, and post that as a comment to the PR.  In addition, we have some other dependencies, so we have to manage it ourselves.

I have adapted the infracost github action to work with this functionality, but am running into a very strange bug.  Here is how I have it configured:

For this example, let's say we have two states we are running, located in these paths:
- `terraform-states/environments/prd/myapp`
- `terraform-states/environments/prd/yourapp`

We run `infracost breakdown --format json --no-color --path ${state} > infracost_breakdown.json` in each of the states, then use the `upload-artifact` action to upload this file to a unique path based on the state path.  We also convert the folder path to a single path (this is leftover from the old infracost action where you had to check out the repo and create a file for the old and new to do the diff, but its still there).

So we get these artifacts:
- `terraform-states-environments-prd-myapp` (zip containing `infracost_breakdown.json`
- `terraform-states-environments-prd-yourapp` (zip containing `infracost_breakdown.json`

Then I have a single github action step to post the comment, where we download these artifacts using the download artifact action into `~/download/infracost`.

The resulting file tree looks like this:
```
.
└── github
    └── home
        └── download
            └── infracost
                ├── terraform-states-environments-prd-myapp
                │   └── infracost_breakdown.json
                └── terraform-states-environments-prd-yourapp
                    └── infracost_breakdown.json
```
At this point I would expect to be able to run `infracost output --format json --path ~/download/infracost/**/*.json` and have it aggregate into a single report, which I can then store and output in various formats to perform the math and post to the PR.

I have adapted the `output` command, duplicating the logic for `infracost_output_cmd`, but this is where I run into issues:

If I run the command as follows, the resulting file consists of the contents of only ONE of the above, not a combination:

```
infracost_output_json_cmd="infracost output --format json --path ~/download/infracost/**/*.json > total.json"
```
The same is true if try any of the following:
```
# Relative path, with quotes
infracost_output_json_cmd="infracost output --format json --path \"~/download/infracost/**/*.json\" > total.json"
# Full path, without quotes
infracost_output_json_cmd="infracost output --format json --path /github/home/download/infracost/**/*.json > total.json"
```

So far, the only way I have found to get it to work is:
```
# Full path, with quotes
infracost_output_json_cmd="infracost output --format json --path \"/github/home/download/infracost/**/*.json\" > total.json"
```

This will give me the full file that I can then use to populate the PR comment as well as use for the math for how much the cost is changing on each PR.

Seems that this is a discrepancy that should be captured by the CLI tool.  As a user, I would expect globbing to function as is defined in the documentation, and that I can use globbing in any form--relative, absolute, quoted, unquoted, etc.  I *might* expect it to take the glob literally if I used single quotes in bash, but even then I think I would want it to find all the files and combine them.

Hopefully that all made sense, would be happy to discuss further with someone if needed.  Thanks!

**Comment by alikhajeh1** [comment]
Thanks for awesome level of details in the issue description!

## Root cause
I think this issue is caused by shells expanding the glob pattern before invoking the CLI, I tested with `zsh 5.7.1 (x86_64-apple-darwin19.0)` and `GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin17.7.0)`:

1. Setup the following dir structure:
```
p1
- p2
  - a.json
  - b.json
- p3
  - c.json
```

2. Type `infracost output --path p1/**/*.json` but do not press enter, instead press tab and notice how the glob pattern expands to `infracost output --path p1/p2/a.json p1/p2/b.json p1/p3/c.json`.

    This is what [this line](https://github.com/infracost/infracost/blob/master/cmd/infracost/output.go#L40) in CLI sees, where the first json file (`p1/p2/a.json`) is the `--path` flag value, and the other 2 are arguments, which are currently not used by the CLI.

3. Run `infracost output --path "p1/**/*.json"` (with quotes) or `infracost output --path p1/\*\*/\*.json` (escaping the *s) and notice how pressing tab does not expand the glob pattern. Both of these runs produce the expected output as the `--path` flag value gets the actual string value. (I think the relative vs absolute paths were a red-herring?) 

## Short term fixes

I've updated the [help text](https://github.com/infracost/infracost/pull/932) and [docs](https://github.com/infracost/docs/pull/88) to show that quotes are needed for this to work properly. Can you please give those PRs a quick review?

## Longer term fixes

A hack could be to update [this line](https://github.com/infracost/infracost/blob/master/cmd/infracost/output.go#L40) to merge the arguments but that prevents us from adding sub-commands in the future:
```
paths, _ := cmd.Flags().GetStringArray("path")
paths = append(paths, args...)
```

Back when we made this, we decided to use `--path` as it was consistent with `infracost breakdown` and `infracost diff` and it didn't block us from adding subcommands like `infracost output subcommand --path...`. If we're sure we're not going to add subcommands to `infracost output`, the proper fix would to make `--path` an argument and not a required flag.

BTW, 1000s of states is interesting, do you see any performance issues with running infracost thousands of times in builds? If so, we'd be happy to dig into them too :)

**Comment by nomeelnoj** [comment]
Hey @alikhajeh1! thanks for the assist here and sorry for not getting back to you sooner.  So far, we have not had ANY issues running infracost.  The logic in our pipeline is configured such that we only run it on states where there are diffs, and while we have 1000s of states, the odds of any single PR touching more than 5-10 are extremely low (we recently changed the entire folder structure of the repo so I had to make changes to EVERY SINGLE STATE, but due to limitations in our build system running the applies, this was a `[ci skip]` situation :stuck_out_tongue_winking_eye:).

I think the most we have run concurrently is probably somewhere around 100-150, and we have not seen any issues whatsoever with the infracost API.  Thanks again for the quick short term fix!
