### ISSUE TITLE
Terragrunt folder structure question

### ISSUE THREAD

**Issue by Macbet** [infracost/infracost#955]
Hello ! I have a question about how infracost works with terragrunt.
The structure of my project looks something like this:
```
prod stage dev test
```
and in each directory there is approximately such a structure
```
├── apps
│   ├── eks-addons
│   │   └── terragrunt.hcl
│   └── irsa
│       └── flux
│           └── terragrunt.hcl
├── eks
│   └── terragrunt.hcl
├── env_values.yaml
├── infracost.yml
├── kms
│   └── eks
│       └── terragrunt.hcl
└── vpc
    └── terragrunt.hcl
```
and when I saw that the new 0.9.7 version added native support for terragrunt, I was very happy that now it's enough just to specify in --path the directory where my environment is located, but because of checking for the presence of **terragrunt.hcl** infracost cli does not want to work with my environments, before I used to mix all possible subdirectories of the environment in config.yaml but it's not very convenient.
Can you tell me if there is any hack so that my config start working?

**Comment by aliscott** [comment]
Thanks @Macbet. At the moment are you able to add a `terragrunt.hcl` file to the top level directory? It can be empty.

Options we are thinking about for the future are:
* Add a `--project-type=terragrunt` flag so you can manually specify the project type
* Run a deep search for any `terragrunt.hcl` files, but we might need to put a time limit/depth limit on it.

Let me know if adding the file is possible and works for you and if you have any thoughts about the above options.

**Comment by Macbet** [comment]
Unfortunately, adding an empty terragrunt. hcl overwrites the configurations of its subfolders. 
I can ofc  drop  root terragrunt.hcl and put local terragrunt.hcl to all subfolders but it will take too much time. 
Thank you very much for the answer I will return to config.yaml with a lot of paths in it

**Comment by alikhajeh1** [comment]
> Run a deep search for any terragrunt.hcl files, but we might need to put a time limit/depth limit on it.

I wonder if we do this and limit to a depth of 5 it catches most projects? Longer term I think I prefer to see costs of all IaC projects in the `--path` by default and have a way to filter on the ones I care about (meaning it might still need to search the dirs to detect their types). The alternative of having `--project-type` override seems ok but then what happens if there are multiple IaC projects? Do I pass both? (e.g. CloudFormation with serverless, or Terraform with K8s).

**Comment by aliscott** [comment]
> Unfortunately, adding an empty terragrunt. hcl overwrites the configurations of its subfolders.

@Macbet out of interest what gets overwritten? Is this because of child dirs having something like:
```hcl
include {
  path = find_in_parent_folders()
}
```

> I wonder if we do this and limit to a depth of 5 it catches most projects?

@alikhajeh1 Yeah I think this could work. The logic in Terragrunt binary itself doesn't have any limit when it's checking, but when using that it's safe to assume you are looking for a Terragrunt project, whereas for Infracost we can't assume that `--path` is Terragrunt. Maybe a depth with a timeout would work in case there's any exceedingly large dirs.

@Macbet I'm going to reopen this (if okay) since I think it's an important issue an imagine other users will come across this.

**Comment by tim775** [comment]
I wrote #966 to help with this by searching for terragrunt.hcls nested up to 5 levels deep from the `--path`.  @Macbet will that fix this issue for you?

**Comment by Macbet** [comment]
I just build it from main and tested it - it works awesome ! Thank you very much! @tim775

**Comment by tim775** [comment]
Great!  This will go out in the next release.

**Comment by alikhajeh1** [comment]
@Macbet just FYI that [v0.9.9](https://www.infracost.io/docs/#1-install-infracost) has been released, it includes this fix.

**Comment by Macbet** [comment]
oh, i use 0.9.8 and it's work from that version :D
